spring:
  application:
    name: course-catalog-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/books
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #this recreates the db, not recommended for prod
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jwt:
    key: ${JWT_KEY}
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000